# Generated by Django 4.0.6 on 2022-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_name', models.CharField(max_length=100)),
                ('Flight_type', models.CharField(choices=[('Economy', 'Economy'), ('First', 'First'), ('Premime Economy', 'Premime Economy'), ('Multiple', 'Multiple'), ('Business', 'Business')], max_length=20)),
                ('Flight_day', models.CharField(choices=[('Wednesday', 'Wednesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Monday', 'Monday')], max_length=30)),
                ('Flight_date', models.DateField()),
                ('Flight_time', models.TimeField()),
                ('Destination', models.CharField(max_length=50)),
            ],
        ),
    ]
