# Generated by Django 4.0.6 on 2022-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_flight_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Date', models.DateField()),
                ('Ticket_type', models.CharField(choices=[('Standard', 'Standard'), ('VIP', 'VIP')], max_length=50)),
                ('Comment', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='flight_schedule',
            name='Flight_day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Monday', 'Monday')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight_schedule',
            name='Flight_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('Multiple', 'Multiple'), ('Premime Economy', 'Premime Economy'), ('First', 'First')], max_length=20),
        ),
    ]
