# Generated by Django 4.0.6 on 2022-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_flight_app', '0002_booking_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='Ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Standard', 'Standard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='flight_schedule',
            name='Flight_day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flight_schedule',
            name='Flight_type',
            field=models.CharField(choices=[('Multiple', 'Multiple'), ('Premime Economy', 'Premime Economy'), ('First', 'First'), ('Business', 'Business'), ('Economy', 'Economy')], max_length=20),
        ),
    ]
